# -*- coding: utf-8 -*-
"""ALS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10VbiG7YaFcvBaK35TNtHWLjlOeY7k005

## PROJET 2: THE STREAMING WAR (RECSYS)
## Dataset: MovieLens 1M
## Algorithme: ALS (Alternating Least Squares)
"""

import pandas as pd
import numpy as np
import scipy.sparse as sparse
!pip install implicit
import implicit
import time
from sklearn.preprocessing import MinMaxScaler

import os
import requests
import zipfile
from io import BytesIO

# ==========================================
# 1. TELECHARGEMENT ET CHARGEMENT DES DONNEES
# ==========================================
def download_movielens():
    url = "https://files.grouplens.org/datasets/movielens/ml-1m.zip"
    data_dir = "ml-1m"

    if not os.path.exists(data_dir):
        print("Téléchargement du dataset MovieLens 1M...")
        r = requests.get(url)
        z = zipfile.ZipFile(BytesIO(r.content))
        z.extractall()
        print("Extraction terminée.")
    return data_dir

data_path = download_movielens()

print("Chargement des fichiers...")
ratings = pd.read_csv(f'{data_path}/ratings.dat', sep='::', header=None,
                      names=['UserID', 'MovieID', 'Rating', 'Timestamp'],
                      engine='python')

movies = pd.read_csv(f'{data_path}/movies.dat', sep='::', header=None,
                     names=['MovieID', 'Title', 'Genres'],
                     engine='python', encoding='latin-1')

# Création de dictionnaires de mapping pour gérer les IDs non continus
# On map les MovieID (ex: 1, 10, 3952) vers des indices de matrice (0, 1, 2...)
unique_movies = movies.MovieID.unique()
movie_to_idx = {o: i for i, o in enumerate(unique_movies)}
idx_to_movie = {i: o for i, o in enumerate(unique_movies)}
idx_to_title = {i: title for i, title in enumerate(movies.Title)}

# Mapping des Users
unique_users = ratings.UserID.unique()
user_to_idx = {o: i for i, o in enumerate(unique_users)}
idx_to_user = {i: o for i, o in enumerate(unique_users)}

# Transformation des colonnes en indices
ratings['movie_idx'] = ratings.MovieID.map(movie_to_idx)
ratings['user_idx'] = ratings.UserID.map(user_to_idx)

print(f"Dataset chargé: {ratings.shape[0]} notes.")
print(f"Utilisateurs: {len(unique_users)}, Films: {len(unique_movies)}")

# Calcul de la sparsité pour le rapport
sparsity = 1 - (len(ratings) / (len(unique_users) * len(unique_movies)))
print(f"Sparsité du dataset: {sparsity:.4%}")

print(movies)

# ==========================================
# 2. CREATION DES MATRICES CSR
# ==========================================
# ALS attend une matrice Interaction (Utilisateurs x Items)
# Pour ALS explicite/implicite, on pondère souvent par la note.
# Ici, on utilise la note comme "confiance" ou valeur brute.

rows = ratings.user_idx
cols = ratings.movie_idx
data = ratings.Rating # On utilise la note (1-5) comme valeur

# Matrice User-Item (pour l'inférence) et Item-User (pour l'entraînement implicit)
user_item_matrix = sparse.csr_matrix((data, (rows, cols)),
                                     shape=(len(unique_users), len(unique_movies)))

# ==========================================
# 3. ENTRAINEMENT DU MODELE ALS
# ==========================================
print("\nEntraînement du modèle ALS...")

# Hyperparamètres
FACTORS = 64        # Dimension latente (complexité des goûts)
REGULARIZATION = 0.1 # Pour éviter le sur-apprentissage
ITERATIONS = 20     # Nombre de passes (convergence)

# Initialisation du modèle (utilisation de CPU optimisé ou GPU si dispo)
# Note: La librairie 'implicit' est très performante.
model = implicit.als.AlternatingLeastSquares(factors=FACTORS,
                                             regularization=REGULARIZATION,
                                             iterations=ITERATIONS,
                                             random_state=42)

# Entraînement (Note: implicit attend Item x User pour l'efficacité)
start_time = time.time()
model.fit(user_item_matrix)
print(f"Modèle entraîné en {time.time() - start_time:.2f} secondes.")

# ==========================================
# 4. FONCTIONS DE RECOMMANDATION (LATENCE & COLD START)
# ==========================================

def get_popular_movies(n=10):
    """ Stratégie Cold Start Zéro: Retourne les films les plus populaires/mieux notés """
    top_movies = ratings.groupby('MovieID').agg({'Rating': ['count', 'mean']})
    top_movies.columns = ['count', 'mean']
    # Score simple : count * mean (pour favoriser les films vus ET aimés)
    top_movies['score'] = top_movies['count'] * top_movies['mean']
    top_ids = top_movies.sort_values('score', ascending=False).head(n).index
    return movies[movies.MovieID.isin(top_ids)][['Title', 'Genres']]

def recommend_for_new_user(new_ratings_dict, n=5):
    """
    Gère le cas 'Live Evaluation' du prof.
    Calcule le vecteur utilisateur à la volée sans ré-entraîner tout le modèle.

    Math: P_u = (Q.T * Q + lambda * I)^-1 * Q.T * R_u
    La librairie 'implicit' gère cette projection mathématique via `recalculate_user`.
    """
    # 1. Création du vecteur sparse pour le nouvel utilisateur
    # new_ratings_dict est sous forme {MovieID: Rating}

    movie_indices = [movie_to_idx[mid] for mid in new_ratings_dict.keys() if mid in movie_to_idx]
    ratings_values = [r for mid, r in new_ratings_dict.items() if mid in movie_to_idx]

    if not movie_indices:
        print("Aucun ID de film reconnu. Application Cold Start global.")
        return get_popular_movies(n)

    # Création d'une matrice sparse 1 x N_Items
    new_user_sparse = sparse.csr_matrix(
        (ratings_values, ([0]*len(movie_indices), movie_indices)),
        shape=(1, len(unique_movies))
    )

    # 2. Inférence Latence Faible : On projette le nouvel utilisateur dans l'espace latent
    # recommend() recalcule le facteur utilisateur P_u basé sur Q existant
    # filter_already_liked_items=True empêche de recommander ce qu'il vient de noter
    ids, scores = model.recommend(userid=0, # ID fictif car on passe user_items
                                  user_items=new_user_sparse,
                                  N=n,
                                  recalculate_user=True)

    # 3. Récupération des titres
    rec_movies = []
    for idx, score in zip(ids, scores):
        movie_id = idx_to_movie[idx]
        title = movies[movies.MovieID == movie_id]['Title'].values[0]
        genre = movies[movies.MovieID == movie_id]['Genres'].values[0]
        rec_movies.append({'Title': title, 'Genre': genre, 'Score': score})

    return pd.DataFrame(rec_movies)

# ==========================================
# 5. SERIALISATION
# ==========================================

import pickle

# 1. Sauvegarde du modèle ALS (fichiers .npz)
model.save("als_model.npz")

# 2. Sauvegarde des mappings et métadonnées (fichiers .pkl)
# Indispensable pour que Streamlit reconnaisse les IDs de MovieLens 1M
metadata = {
    "movie_to_idx": movie_to_idx,
    "idx_to_movie": idx_to_movie,
    "unique_movies": unique_movies,
    "sparsity": sparsity
}

with open("als_metadata.pkl", "wb") as f:
    pickle.dump(metadata, f)

print("Système sérialisé : 'als_model.npz' et 'als_metadata.pkl' sont prêts.")

# ==========================================
# 6. INTERFACE DE TEST (SIMULATION LIVE)
# ==========================================

print("\n=== SYSTEME PRÊT POUR L'EVALUATION LIVE ===")
print("Tapez 'exit' pour quitter.")

while True:
    print("\n--- Nouveau test utilisateur ---")
    search = input("Entrez une partie du titre d'un film (ex: Toy Story) : ")
    if search.lower() == 'exit': break

    # Recherche du film
    matches = movies[movies['Title'].str.contains(search, case=False, regex=False)]

    if matches.empty:
        print("Aucun film trouvé.")
        continue

    # Affichage des 5 premiers résultats pour choix
    print("\nFilms trouvés :")
    for idx, row in matches.head(5).iterrows():
        print(f"ID: {row['MovieID']} | {row['Title']}")

    try:
        selection_id = int(input("\nEntrez l'ID du film que vous voulez noter : "))
        rating = float(input("Votre note (1-5) : "))

        # Simulation Cold Start / Live Update
        start_rec = time.time()

        # On passe un dictionnaire {MovieID: Note}
        recommendations = recommend_for_new_user({selection_id: rating}, n=5)

        latence = (time.time() - start_rec) * 1000 # ms

        print(f"\n>>> Recommandations générées en {latence:.2f} ms :")
        print(recommendations)

        # Explication pour le rapport (à afficher pour le prof)
        print("\n[INFO DEBUG] Stratégie employée :")
        print("1. Projection du vecteur de vos notes sur la matrice Q (Films) existante.")
        print("2. Calcul : p_new = (Q.T*Q + lambda*I)^-1 * Q.T * r_new")
        print("3. Dot product avec tous les films pour trouver les plus proches.")

    except ValueError:
        print("Entrée invalide.")
    except Exception as e:
        print(f"Erreur : {e}")